# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
   - cron: "0 0 */1 * *"
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
       python -m pip install --upgrade pip
        pip install feedparser
    - name: Run Update Python Script
      run: |
        python HongMinyeong.py ## 실행시킬 .py이름
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u hongminyeong --password-stdin
      
    - name: Get the latest tag
      id: get_latest_tag
      run: |
        echo "Fetching latest tag..."
        TAG=$(curl -s https://hub.docker.com/v2/repositories/hongminyeong/pythonapp/tags | jq -r '.results[0].name' | sed 's/[^0-9]*//g')
        echo "Latest tag: $TAG"
        if [[ -z "$TAG" ]]; then
          echo "TAG=0" >> $GITHUB_ENV
        else
          echo "TAG=$TAG" >> $GITHUB_ENV
        fi
    - name: Set new tag
      id: set_new_tag
      run: |
        NEW_TAG=$((TAG + 1))
        echo "New tag: $NEW_TAG"
        echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV

    - name: Build Docker Image
      run: |
        docker build -t myflaskapp .
        docker tag myflaskapp hongminyeong/pythonapp:${{ env.NEW_TAG }}
        docker push hongminyeong/pythonapp:${{ env.NEW_TAG }}

    - name: Run Trivy Vulnerability Scan
      run: |
        docker run --rm -v $(pwd):/project aquasec/trivy --quiet --severity HIGH,CRITICAL filesystem /project
        docker run --rm aquasec/trivy image hongminyeong/pythonapp:${{ env.NEW_TAG }}
        
    - name: Update README.md file
      run: |
        git pull
        git add .
        git diff
        git config --local user.email "minyung1240@daum.nat"
        git config --local user.name "HongMinyeong"
        git commit -m "Update README.md"
        git push
